<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Component Icon</name>
   <tag></tag>
   <elementGuidId>439072d8-e9d3-4fb6-bb42-e08a7a4bc76a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EditableToolbar']/button/coral-icon[@aria-label='add']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.coral3-Button.coral3-Button--quiet.cq-editable-action > coral-icon.coral3-Icon.coral3-Icon--sizeS.coral3-Icon--add</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>coral-icon</value>
      <webElementGuid>7e2cc4c5-a004-4cad-9fc6-37e29346529f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral3-Icon coral3-Icon--sizeS coral3-Icon--add</value>
      <webElementGuid>f6e9545a-70d0-47e9-be94-59792896de9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>22830d4f-ef25-428d-b343-c34982cd9698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>672f1d7b-0733-40a7-8273-36bb72f52dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoarialabel</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>6fe562da-916d-4402-bfe6-4f1d2d872267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1f0abd42-736d-4977-a483-2ee7d5a59d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>9f11f2b1-6700-4310-a128-cfb2522ec00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EditableToolbar&quot;)/button[@class=&quot;coral3-Button coral3-Button--quiet cq-editable-action&quot;]/coral-icon[@class=&quot;coral3-Icon coral3-Icon--sizeS coral3-Icon--add&quot;]</value>
      <webElementGuid>2aa5c559-1f99-4ffe-81d3-c911598b24f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EditableToolbar']/button/coral-icon</value>
      <webElementGuid>88aa234d-a436-4497-8766-ec35aa3d5754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button/coral-icon</value>
      <webElementGuid>8c403ebd-3fa8-4fb3-a9bd-af1d45320087</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
