<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Drag components here</name>
   <tag></tag>
   <elementGuidId>78b40b60-5dfa-4310-a6db-44278350124c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[@data-text=&quot;Drag components here&quot;])[last()]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cq-Overlay.cq-Overlay--component.cq-droptarget.cq-Overlay--placeholder.is-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>089c6158-65e8-45a3-96fa-71d97eab5331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>Editable</value>
      <webElementGuid>67b0e2d0-f980-4dc8-84bd-d3f630cf6a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>/content/www/wwwjalcojp/ar/ja/author-test/adobe/testheader/jcr:content/root/contents/responsivegrid/*</value>
      <webElementGuid>5e102fd9-582c-47f9-952d-ff6d470c1c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>e47511e7-a0c3-4d75-9370-088cabe668aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>37615807-e34d-494a-985b-f8f2fd7320fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d1cd6f6-a993-4dba-9fd1-0e9293f64e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>Drag components here</value>
      <webElementGuid>7f50fe80-8db1-4617-abab-33703561ee2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Layout Container [Root]</value>
      <webElementGuid>8e0af3df-2d25-4893-9a0d-d1b262c0e1de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cq-Overlay cq-Overlay--component cq-droptarget cq-Overlay--placeholder is-hover</value>
      <webElementGuid>e462719d-9ffd-402a-af35-45e5ae36518e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OverlayWrapper&quot;)/div[@class=&quot;cq-Overlay cq-Overlay--component cq-Overlay--container&quot;]/div[@class=&quot;cq-Overlay cq-Overlay--component cq-droptarget cq-Overlay--placeholder is-hover&quot;]</value>
      <webElementGuid>fc4244f8-ae95-40fb-ac24-30158929c570</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OverlayWrapper']/div[2]/div[20]</value>
      <webElementGuid>fece87ad-7d73-46a7-8633-8d5061894b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[20]</value>
      <webElementGuid>b56e8e80-7bcf-4748-b842-e37c3267a149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Layout Container [Root]']</value>
      <webElementGuid>5460c41c-eedb-4465-8bb1-ac9ae70f0715</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
