<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JAL-0001 column</name>
   <tag></tag>
   <elementGuidId>5501bf00-77bf-479c-9640-41b1e7859e99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//coral-selectlist-item[text()='JAL-0001 column']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>coral-selectlist-item.coral3-SelectList-item.is-highlighted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>coral-selectlist-item</value>
      <webElementGuid>a0d62c3c-93ad-4a7d-985e-e77ea80d816e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral3-SelectList-item is-highlighted</value>
      <webElementGuid>a9998f09-86f5-4757-89f6-e563f71271b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d9879dc6-a309-446f-bb1b-c80934951427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/apps/jalcms/global/components/content/column</value>
      <webElementGuid>c036660c-6733-466d-9b03-fa77bd6ad834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d1417737-8290-4c31-a8d9-52982b853d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b9907f3d-f2f7-4fd7-a6f7-cfd9baadce80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f5e1e924-e4fb-40cf-a9f1-e816ebfeff3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JAL-0001 column</value>
      <webElementGuid>c0cfc187-d743-40bb-9b1c-ec05766bd79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coral-id-623&quot;)/coral-selectlist-item[@class=&quot;coral3-SelectList-item is-highlighted&quot;]</value>
      <webElementGuid>3cbf7fb1-7279-47da-bcb2-7f1812f83eed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//coral-selectlist-item[@value='/apps/jalcms/global/components/content/column']</value>
      <webElementGuid>44129fbd-110f-4279-ada3-1cb18851150e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//coral-selectlist-group[@id='coral-id-623']/coral-selectlist-item</value>
      <webElementGuid>9ad9d00c-9035-4935-b26c-5c7009d6a110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insert New Component'])[1]/following::coral-selectlist-item[1]</value>
      <webElementGuid>c3f2c2df-558c-4af3-97e0-1dcf5a71377c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Styles'])[2]/following::coral-selectlist-item[1]</value>
      <webElementGuid>76b80951-3e53-4a7c-a85a-e2b5988bb91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAL-0002 list'])[1]/preceding::coral-selectlist-item[1]</value>
      <webElementGuid>b350caf2-7641-4934-9909-03df1e4194a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAL-0003 link list'])[1]/preceding::coral-selectlist-item[2]</value>
      <webElementGuid>49044a46-9b6e-41ff-a66c-36ecbea136bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//coral-selectlist-group/coral-selectlist-item</value>
      <webElementGuid>cc3d38b1-67ca-4c1f-bd90-7afc0b013fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//coral-selectlist-item[(text() = 'JAL-0001 column' or . = 'JAL-0001 column')]</value>
      <webElementGuid>bfea75d9-1b4d-4ea7-b15a-28ee60053e4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
