<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FinalCreatePage</name>
   <tag></tag>
   <elementGuidId>4f5e8294-e689-4d14-9eaa-9f595f4f8b04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button//*[text()='Create']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
