<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JAL-0001Page</name>
   <tag></tag>
   <elementGuidId>522ff916-d1c0-4096-ae12-70dfdb1f6151</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@title=&quot;Test2&quot;]//parent::coral-columnview-item-content//preceding-sibling::coral-columnview-item-thumbnail//img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
