<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>moreIcon</name>
   <tag></tag>
   <elementGuidId>addfaa68-a8cb-4907-8f5d-e0b166e06709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button//*[@icon=&quot;more&quot;])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
