<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OpenCreatedPage</name>
   <tag></tag>
   <elementGuidId>f57f6035-e2be-4c95-ac6f-79239871fedc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button//*[text()='Open']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
