<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TestHeaderPage_Link</name>
   <tag></tag>
   <elementGuidId>a75f67ef-a4c7-4a7b-9834-b5fb8b96b209</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coral-id-417</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//coral-columnview-item-thumbnail[@id='coral-id-417']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>coral-columnview-item-thumbnail</value>
      <webElementGuid>11a31778-fea0-492b-ad7e-b9e00aafac4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coral-id-417</value>
      <webElementGuid>b80d68a2-7562-4321-8e1b-6012263a0b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coral-id-417&quot;)</value>
      <webElementGuid>11b9e5ac-87d6-4b31-b5d4-0dce0276d1bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//coral-columnview-item-thumbnail[@id='coral-id-417']</value>
      <webElementGuid>fa1f0776-4126-4bc9-b9c4-931b44555934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//coral-columnview-item[@id='coral-id-420']/coral-columnview-item-thumbnail</value>
      <webElementGuid>58cecc16-68a8-4ead-b728-a834cd87af72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading more items'])[7]/following::coral-columnview-item-thumbnail[1]</value>
      <webElementGuid>1df617a5-3c7d-4915-b5dc-dd67f55850c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='adobe'])[4]/following::coral-columnview-item-thumbnail[1]</value>
      <webElementGuid>1177698c-58dc-4a10-828a-cc3b79301e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestHeader'])[2]/preceding::coral-columnview-item-thumbnail[1]</value>
      <webElementGuid>2e8a5742-8ad5-474f-bbf3-2c434d2f1623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testheader'])[1]/preceding::coral-columnview-item-thumbnail[1]</value>
      <webElementGuid>cdb752ff-766b-4ecc-a474-04bf82081d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//coral-columnview-column[7]/coral-columnview-column-content/coral-columnview-item/coral-columnview-item-thumbnail</value>
      <webElementGuid>c89d7851-a4f0-4c21-82ad-3b9cdc830422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//coral-columnview-item-thumbnail[@id = 'coral-id-417']</value>
      <webElementGuid>49411b7e-e855-4533-bd11-54df9867f2d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
