<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>www_Link</name>
   <tag></tag>
   <elementGuidId>723202dc-b84c-48c3-b2eb-7d8e86ecbfbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coral-id-19 > div.foundation-collection-item-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//coral-columnview-item-content[@id='coral-id-19']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dba5a02a-cf90-4eae-99f4-93402765a958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>foundation-collection-item-title</value>
      <webElementGuid>cdd5dfa5-b424-4d9c-bcaa-df3f43d33c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>9d5fede8-4212-4844-a88b-eeef8102cb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>www</value>
      <webElementGuid>3a3665c6-d4c9-4f97-8d57-22ab59060cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            www
        </value>
      <webElementGuid>ce5585d4-b584-4b06-b6d7-1f4ba47ff0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coral-id-19&quot;)/div[@class=&quot;foundation-collection-item-title&quot;]</value>
      <webElementGuid>28126be7-5014-4f2a-b5cf-e205ff618da7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//coral-columnview-item-content[@id='coral-id-19']/div</value>
      <webElementGuid>5fb3fd99-c69c-448a-9448-e7378d793588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='community'])[2]/following::div[1]</value>
      <webElementGuid>9626c35c-0819-41a3-ab31-742f62d9782a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='campaigns'])[1]/following::div[2]</value>
      <webElementGuid>385e632d-b43e-4fec-a66e-d3e82b94c7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='language-masters'])[2]/preceding::div[1]</value>
      <webElementGuid>0bff7427-ecb1-4e02-9957-37d2eb20ac35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAL RM AEM Site'])[2]/preceding::div[2]</value>
      <webElementGuid>b29f0ac6-b9f3-411e-b659-8cdf32c1aa28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//coral-columnview-item[3]/coral-columnview-item-content/div</value>
      <webElementGuid>4bb86fb4-efcf-4815-a40a-d34f1c587df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'www' and (text() = '
            www
        ' or . = '
            www
        ')]</value>
      <webElementGuid>a5425cea-4f52-4fc0-bc9d-ac956673619f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
